### ISSUE TITLE
static proptypes

### ISSUE THREAD

**Issue by sunnylqm** [este/native#14]
Wow, a new transformer.js! Fresh and clean!    
However, are "static proptypes" really supported now? I had always got "Unexpected token" when I tried this version.
Besides, any suggestions on bundling js now? Since webpack was dropped...

**Comment by grabbou** [comment]
Well, just use native `react-native bundle` ;)

**Comment by grabbou** [comment]
>  had always got "Unexpected token" when I tried this version.

Please check https://github.com/este/native#common-problems, looks like your issue might be related to the same thing happening to es6 modules. Try to reset packager cache and run it again from XCode. They should be enabled, you can always tweak the list in `whitelist` :)

**Comment by sunnylqm** [comment]
Thanks for you explanation! I've tried resetCache, but still not work. I'll check it again later.    
I am not a native english-speaker, so forgive my wording:)

**Comment by grabbou** [comment]
Me neither, so welcome to the club :dart:

**Comment by grabbou** [comment]
Fixed.
