### ISSUE TITLE
Add basic Android support

### ISSUE THREAD

**Issue by grabbou** [este/native#20]
Tomorrow, to see how it works, after #19 merged.

**Comment by ilionic** [comment]
So Redux is going to be part of Este as improvement of current flux implementation? 
Curious about your decisions / opinions regarding those and how easy they integrate?

**Comment by grabbou** [comment]
> So Redux is going to be part of Este as improvement of current flux implementation? 
Yes, just because we want it under the hood to benefit from already impressive ecosystem and libraries

> how easy to integrate?
There will be no real difference in your components. Actions will require a small `rewrite`, mainly to reorganise them. No logic changes so it's quite safe :)

There will be no `this.createActions()` and no issues with static hooks. The current PR with Redux is a complete one so feel free to investigate it :)

**Comment by grabbou** [comment]
Implemented in PR and will be merged soon.
