### ISSUE TITLE
App not starting in simulator

### ISSUE THREAD

**Issue by michalvalasek** [este/native#7]
1. cloned the repo
2. run `npm install` (success)
3. opened the project in Xcode (`open este.xcodeproj`)
4. run `npm start` (success)
5. getting red screen with `undefined is not an object (evaluating 'Dimensions.get')"` (even after reload)

![screen shot 2015-07-16 at 16 20 10](https://cloud.githubusercontent.com/assets/312155/8725794/938bda5e-2bd6-11e5-9f77-bf3e051e06c0.png)

**Comment by benox3** [comment]
+1

**Comment by benox3** [comment]
+1

**Comment by grabbou** [comment]
Yeah sorry about that, will push fix by midday :)
